version: '3.9'
services:

  front-react:
    build:
      context: ./client

    environment:
      NODE_ENV: development
      NODE_OPTIONS: --openssl-legacy-provider

    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "5000:3000"

  server-dev:
    build:
      context: ./server
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      db-dev:
        condition: service_healthy
      mongo-dev:
        condition: service_started
    volumes:
      - ./var/www/html/images:/var/www/html/images
      - ./server:/server
      - /server/node_modules
      - ./.env:/server/.env
    restart: always

  mongo-dev:
    image: mongo:6.0
    ports:
      - "27017:27017"
    restart: always

  db-dev:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: todo-dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo-dev"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: always

volumes:
  server-dev:
